# Generated by Django 3.2.8 on 2022-02-03 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/doctor/blog/')),
                ('category', models.CharField(choices=[('Mental health', 'Mental health'), ('Heart disease', 'Heart disease'), ('Covid-19', 'Covid-19'), ('Immunization', 'Immunization')], max_length=50, verbose_name='Role')),
                ('summary', models.CharField(blank=True, max_length=100, verbose_name='Summary')),
                ('content', models.TextField(blank=True, max_length=100, verbose_name='Content')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form.doctor')),
            ],
        ),
    ]
