# Generated by Django 3.2.8 on 2022-02-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_blogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
