# Generated by Django 3.2.8 on 2022-02-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_rename_blogs_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='complete',
            field=models.CharField(blank=True, choices=[('Save as a draft', 'Save as a draft'), ('Post content as a blog', 'Post content as a blog')], max_length=50, null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('Mental health', 'Mental health'), ('Heart disease', 'Heart disease'), ('Covid-19', 'Covid-19'), ('Immunization', 'Immunization')], max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title'),
        ),
    ]
