# Generated by Django 3.2.8 on 2022-02-04 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20220203_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='complete',
        ),
        migrations.AddField(
            model_name='blog',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='publish',
            field=models.DateField(default=datetime.datetime(2022, 2, 4, 13, 22, 42, 943663, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
