# Generated by Django 3.2.8 on 2022-02-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20220204_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='publish',
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('Mental health', 'Mental health'), ('Heart disease', 'Heart disease'), ('Covid-19', 'Covid-19'), ('Immunization', 'Immunization')], max_length=50, null=True, verbose_name='Category '),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, max_length=100, verbose_name='Content '),
        ),
        migrations.AlterField(
            model_name='blog',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Draft '),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/doctor/blog/', verbose_name='Image '),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(blank=True, max_length=100, verbose_name='Summary '),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title '),
        ),
    ]
