# Generated by Django 3.2.8 on 2022-02-08 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20220204_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(blank=True, max_length=50, verbose_name='Required speciality ')),
                ('date_of_appointment', models.CharField(blank=True, max_length=50, verbose_name='Date of appointment ')),
                ('Starttime_of_appointment', models.CharField(blank=True, max_length=50, verbose_name='Start-time of appointment ')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form.doctor')),
            ],
        ),
    ]
