# Generated by Django 3.2.8 on 2022-02-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_auto_20220208_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date_of_appointment',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Starttime_of_appointment',
            field=models.DateTimeField(blank=True, max_length=50, verbose_name='Start-time of appointment '),
        ),
    ]
