# Generated by Django 3.2.8 on 2022-10-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20220210_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Starttime_of_appointment',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Start Date/Time of appointment '),
        ),
    ]
